### ISSUE TITLE
let in for loop

### ISSUE THREAD

**Issue by kimgysen** [jmcriffey/es6-fiddle-web#10]
When running the following code: 

    var i=0;
    for ( let i=i ; i < 10 ; i++ ) {
        console.log(i);
    } 

Nothing is outputted in the console. 
http://www.es6fiddle.net/ifefmsk6/

**Comment by jmcriffey** [comment]
That is interesting. It looks like it has something to do with Traceur. I just updated everything to use Babel instead and it seems like the issue is fixed.
