### ISSUE TITLE
Is this maintained anymore?

### ISSUE THREAD

**Issue by joshghent** [jmcriffey/es6-fiddle-web#11]
Hey,

Is this project maintained anymore?

I've found a couple bugs with the site and wanted to fix them.

In the process I would update to all the newest dependencies and update code mirror.

I'm happy to fork it and do that if it will get merged :)

**Comment by jmcriffey** [comment]
Yep, I'm up for fixing bugs and updated deps. I think we are stuck on Babel 5 though, right? From what I understand, they took out support for in-browser transformations sometime during Babel 6.

**Comment by joshghent** [comment]
@jmcriffey Thanks for the quick reply!

I'll take a look into it and report back. Are you happy for me to go ahead with those changes though?

**Comment by jmcriffey** [comment]
Yeah, those sound good to me!
