### ISSUE TITLE
ES6Fiddle is down and HTTPS has become invalid

### ISSUE THREAD

**Issue by joshghent** [jmcriffey/es6-fiddle-web#17]
Hi there,

It appears as if there is an issue with the HTTPS certificate no longer being valid.

Further to this the heroku app itself appears to be down.

**Comment by jeffrifwald** [comment]
Well damn, it looks like the Compose/MongoHQ database removed their free tier and deleted all the es6fiddle data along with it. I'll have to think about if it is worth it to set up again.

**Comment by joshghent** [comment]
You're kidding! That's unbelievable!

Was this hosted on Heroku. I have a couple apps hosted on there with mongo and they seem to be chugging away.

Perhaps I can get it setup again?

**Comment by ova2** [comment]
I have referenced ES6 fiddles in my online presentations (ECMAScript 2015 features). Now es6fiddle is offline :-(

What is the problem to get it running again? I haven't understood.

**Comment by joshghent** [comment]
I can get it running on a heroku instance (not on the ES6 fiddle domain mind) if you need others to have access to it.
Otherwise I would recommend spinning up a local instance yourself.
As for your fiddles data perhaps @jmcriffey can shed more like on what has happened to all the data and if it will come back up

**Comment by ova2** [comment]
It would be nice to get ES6 fiddle domain running again because we need the old saved fiddles. I guess we don't have old fiddles on Heroku. Right? E.g. here http://ova2.github.io/es6-presentations/slides/destructuring/index.html#12 I have a link ES6 Fiddle and want to restore the old saved fiddle (on Heroku or somewhere else).

Thanks.

**Comment by jeffrifwald** [comment]
From what I understand, the data has been deleted and is not recoverable. I missed an email that said I had a couple of weeks to migrate everything, so it looks like all the saved fiddles have been permanently deleted.

**Comment by joshghent** [comment]
@jmcriffey Oops... Are you able to get it setup again?

**Comment by joshghent** [comment]
Bump @jmcriffey

**Comment by jeffrifwald** [comment]
Sorry guys, I've been pretty busy over the last couple of weeks. Unfortunately the saved fiddles have been deleted. I'm not certain it makes sense to continue supporting the site, as it looks like cheap database solutions are subject to random destruction.

I think es6fiddle less and less relevant these days, since most browsers now support most of the updated syntax. Also, jsfiddle has a babel transpiler option these days too. I think jsfiddle is a much more stable solution for the long term.

I might just redirect the domain name to jsfiddle. @joshghent Thoughts?

**Comment by joshghent** [comment]
@jmcriffey That's fine. Hope you had a good holidays 😀 

I am happy to take over support for the project. I agree that jsfiddle is a lot bigger but that doesn't mean to say there isn't a place for esfiddle with all the new ES7 and ES8 features coming soon.

I have the domain esfiddle.net which we could use. I think it would be wise to transition away from ES6 fiddle as that ties it to a specific version of ecmascript.

Perhaps we can arrange a project and domain transfer so I can get the site launched again and moved to a separate group repo?

**Comment by joshghent** [comment]
@jmcriffey I will probably setup the project as an organization.

I have a lot of ideas on how we can get people to contribute and use the site.

Let me know what you would like to do.

**Comment by joshghent** [comment]
@jmcriffey Bump 👍

**Comment by joshghent** [comment]
Hi Guys,

I have made a new organisation esfiddle and transferred my local repo to that organisation.

I am aiming to

1. Get more people to contribute - improve the contribute.md, get listed on up-for-grabs etc.
2. Build in ES7 and then ES8 features as they come around
3. Many more things!

I am coordinating to get the es6fiddle domains transferred.

Please see here as this repository will be updated from now on https://github.com/esfiddle/es6-fiddle-web

**Comment by ghost** [comment]
Your site es6fiddle.net is referenced on page 348 of the book: Angular 2 Development with Typescript by Manning publications. However the site is now down? I suggest adding a redirect to your new location esfiddle.net. Best regards, Cody.

**Comment by joshghent** [comment]
Hi @ctolene - Unfortunatly the database from es6fiddle was lost. However, I have forked this off into a new project called [esfiddle.net](https://esfiddle.net/) which has all the original features of the site and more.

We are also looking for contributors on our github project [here](https://github.com/esfiddle/esfiddle)

**Comment by getify** [comment]
I appreciate what happened and why you moved the project to a new site.

However, is there no way to redirect the "es6fiddle.net" domain to "esfiddle.net"? I've sold about 100,000 copies of my @YDKJS books, which mention "es6fiddle.net" in them multiple times.

**Comment by joshghent** [comment]
@getify Hi Kyle, I'm honoured that you've used ESFiddle in your books - I've read them myself and am a huge fan. 

With that said, I don't have access to the domain es6fiddle.net personally (but will get it as soon as it becomes available). Even with the domain however, the database for the app was deleted when the host expired. 

My personal email is me@joshghent.com - perhaps we can speak there and I will try and make sure we can restore any lost snippets as I'd love for esfiddle to be used in YDKJS.

**Comment by getify** [comment]
I don't recall that I linked to any specific fiddles, just mentioned the site by URL several times, for people to use when they wanted to see how JS was being transpiled. So really, it's just the redirect from the old domain the new one, that would save all people who have copies of the books from having a dead link.

It's a shame there's not access to that domain. Who has it?

**Comment by joshghent** [comment]
@getify Yeah I just did a quick search and luckily it seems as if you just linked to the site directly.

@jmcriffey Has the domain. Luckily it expires on 2018-02-10. So I will backorder it or buy it if it becomes available. Hopefully it expires and is not set to autorenew (although godaddy, the registrar, does this automatically usually).
I have attempted to contact him multiple times on twitter, github and via email with no response.

In the mean time, I hope you can make use of [esfiddle.net](https://esfiddle.net/) going forward. Sorry I don't have a better solution for now. Trust me, I want this as much as you! 👍
